# Generated by Django 3.0 on 2020-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200827_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile',
            new_name='profs',
        ),
        migrations.AlterField(
            model_name='bdata',
            name='pic',
            field=models.ImageField(upload_to='media/pics/'),
        ),
    ]
